sudo: required
dist: bionic
addons:
  chrome: stable
language: node_js
node_js:
  - 12
  - 14
cache: npm
install:
  - cp package.json.dist package.json
  - npm install
script:
  - xvfb-run npm run ci
