version: 2.1

orbs:
  browser-tools: circleci/browser-tools@1.4.1

jobs:
  test:
    docker:
      - image: cimg/node:16.18-browsers
        auth:
          username: $DOCKER_HUB_USERNAME
          password: $DOCKER_HUB_ACCESS_TOKEN
    steps:
      # https://stackoverflow.com/a/75738251/2803757 – this lib's required for Chrome 111+
      # and not in the current base image.
      - run: |
          cd /tmp;
          wget http://archive.ubuntu.com/ubuntu/pool/main/libu/libu2f-host/libu2f-udev_1.1.4-1_all.deb;
          sudo dpkg -i libu2f-udev_1.1.4-1_all.deb;
          cd ~/project
      - browser-tools/install-chrome:
          chrome-version: 113.0.5672.63 # https://github.com/puppeteer/puppeteer/blob/main/versions.js # https://github.com/puppeteer/puppeteer/blob/main/versions.js
      - browser-tools/install-chromedriver
      - checkout
      - restore_cache:
          keys:
            - v3-dependencies-{{ checksum "package-lock.json" }}
      - run: PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=1 npm install --quiet
      - save_cache:
          paths:
            - node_modules
          key: v3-dependencies-{{ checksum "package-lock.json" }}
      - run: npm run ci

workflows:
  test:
    jobs:
      - test:
          context:
            - docker-hub-creds
