version: 2.1

orbs:
  browser-tools: circleci/browser-tools@1.4.8

jobs:
  test:
    docker:
      - image: cimg/node:20.16-browsers
        auth:
          username: $DOCKER_HUB_USERNAME
          password: $DOCKER_HUB_ACCESS_TOKEN
    steps:
      # https://stackoverflow.com/a/75738251/2803757 – these libs are needed for Chrome[driver] as of Nov '23.
      - run: "sudo apt -y update && sudo apt-get install -y libu2f-udev libvulkan1"
      - browser-tools/install-chrome:
          chrome-version: 127.0.6533.119 # https://github.com/puppeteer/puppeteer/blob/main/versions.json
      - browser-tools/install-chromedriver
      - checkout
      - run: PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=1 npm install --quiet
      - run: npm run ci

workflows:
  test:
    jobs:
      - test:
          context:
            - docker-hub-creds
