version: 2.1

orbs:
  browser-tools: circleci/browser-tools@1.5.0

jobs:
  test:
    resource_class: large
    docker:
      - image: cimg/node:22.13-browsers
        auth:
          username: $DOCKER_HUB_USERNAME
          password: $DOCKER_HUB_ACCESS_TOKEN
    steps:
      # https://stackoverflow.com/a/75738251/2803757 – these libs are needed for Chrome[driver] as of Nov '23.
      - run: "sudo apt -y update && sudo apt-get install -y libu2f-udev libvulkan1"
      - browser-tools/install-chrome:
          chrome-version: 132.0.6834.110 # https://github.com/puppeteer/puppeteer/blob/main/versions.json
      - browser-tools/install-chromedriver
      - checkout
      - restore_cache:
          keys:
            - node22-{{ checksum "package-lock.json" }}
      - run:
          name: Install dependencies
          command: PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=1 npm install --quiet
      - save_cache:
          paths:
            - node_modules
          key: node22-{{ checksum "package-lock.json" }}
      - run:
          name: Lint
          command: npm run lint
      - run:
          name: Unit test
          command: npm run test:once
      - run:
          name: Start app for e2e's
          command: npm run start
          background: true
      - run:
          name: Wait for app to be reachable
          command: |
            for i in `seq 1 30`;
            do
              nc -z localhost 4200 && echo Ready! && exit 0
              echo -n .
              sleep 1
            done
            echo Failed waiting for app && exit 1
      - run:
          name: e2e test
          command: npm run e2e

workflows:
  all:
    jobs:
      - test:
          context:
            - docker-hub-creds
