version: 2.1

jobs:
  test:
    docker:
      - image: thebiggive/donate-frontend-ci:latest
        auth:
          username: $DOCKER_HUB_USERNAME
          password: $DOCKER_HUB_ACCESS_TOKEN
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package-lock.json" }}
      - run: npm install --quiet
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package-lock.json" }}
      - run: xvfb-run npm run ci

workflows:
  test:
    jobs:
      - test:
          context:
            - docker-hub-creds
